# Generated by Django 3.2.6 on 2021-11-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
