# Generated by Django 3.2.6 on 2021-11-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_status_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='status',
        ),
    ]
